export const GAME_MAKE_MOVE = 'GAME_MAKE_MOVE';
export const GAME_TOGGLE_SORT = 'GAME_TOGGLE_SORT';
export const GAME_JUMP_TO = 'GAME_JUMP_TO';
export const GAME_SAVE_HISTORY = 'GAME_SAVE_HISTORY';
export const GAME_SET_PLAYER_SIDE = 'GAME_SET_PLAYER_SIDE';

export const SETTING_SET_GAME_MODE = 'SETTING_SET_GAME_MODE';
export const SETTING_SET_FIELD_SIZE = 'SETTING_SET_FIELD_SIZE';
export const SETTING_SET_AI_DIFFICULTY = 'SETTING_SET_AI_DIFFICULTY';

export const AI_SET_AI_PLAYER_UNITS = 'AI_SET_AI_PLAYER_UNITS';
export const AI_SET_PLAYER_UNITS = 'AI_SET_PLAYER_UNITS';
export const AI_SET_AVAILABLE_MOVES = 'AI_SET_AVAILABLE_MOVES';
export const AI_SET_ENEMY = 'AI_SET_ENEMY';
export const AI_SET_CURRENT_INDEX = 'AI_SET_CURRENT_INDEX';
export const AI_ADD_WAY_TO_LIST = 'AI_ADD_WAY_TO_LIST';
export const AI_CLEAR_WAY_LIST = 'AI_CLEAR_WAY_LIST';

export const VICTORY_SET_LIST_OF_WINNING_LINES = 'VICTORY_SET_LIST_OF_WINNING_LINES';

