export const GAME_SET_STATE = 'GAME_SET_STATE';
export const GAME_TOGGLE_SORT = 'GAME_TOGGLE_SORT';
export const GAME_JUMP_TO = 'GAME_JUMP_TO';
export const GAME_SAVE_HISTORY = 'GAME_SAVE_HISTORY';
export const GAME_SET_PLAYER_SIDE = 'GAME_SET_PLAYER_SIDE';

export const SETTING_SET_GAME_MODE = 'SETTING_SET_GAME_MODE';
export const SETTING_SET_FIELD_SIZE = 'SETTING_SET_FIELD_SIZE';

export const SETTING_SET_AI_DIFFICULTY = 'SETTING_SET_AI_DIFFICULTY';